#!/usr/bin/env python
# Copyright (c) 2016, Kevin Rodgers
# Released subject to the New BSD License
# Please see http://en.wikipedia.org/wiki/BSD_licenses

from active_mail_filter.server import run_daemon

if __name__ == '__main__':
    try:
        run_daemon()
    except KeyboardInterrupt:
        pass
