#!/usr/bin/env python
# Copyright (c) 2016, Kevin Rodgers
# Released subject to the New BSD License
# Please see http://en.wikipedia.org/wiki/BSD_licenses

from active_mail_filter.commands import modify_rule

if __name__ == '__main__':
    try:
        modify_rule()
    except KeyboardInterrupt:
        pass
