#! /bin/sh

### BEGIN INIT INFO
# Provides:        amf_daemon
# Default-Start:    2 3 4 5
# Default-Stop:
# Short-Description:    Active Mail Filtering Daemon
### END INIT INFO

set -e

# /etc/init.d/ssh: start and stop active mail filtering daemon

test -x /usr/local/bin/amf_daemon || exit 0

umask 022

if test -f /etc/default/ssh; then
    . /etc/default/ssh
fi

. /lib/lsb/init-functions

start_amf() {
    log_daemon_msg "Starting Active Mail Filtering Daemon" "amf_daemon" || true
    if start-stop-daemon --start --quiet --oknodo --retry 30 --pidfile /var/run/amf.pid --exec /usr/local/bin/amf_daemon; then
        log_end_msg 0 || true
    else
        log_end_msg 1 || true
    fi
    amf_start_daemon
}

stop_amf() {
    log_daemon_msg "Stopping Active Mail Filtering Daemon" "amf_daemon"
    amf_stop_daemon
    if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/amf.pid; then
        log_end_msg 0 || true
    else
        log_end_msg 1 || true
    fi
}

status_amf() {
    status_of_proc -p /var/run/amf.pid /usr/local/bin/amf_daemon amf_daemon
    return $?
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/usr/local/bin"

case "$1" in
  start)
    start_amf()
    ;;
  stop)
    stop_amf()
    ;;
  restart)
    start_amf()
    stop_amf()
    ;;
  status)
    status_amf()
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/amf_daemon {start|stop|restart|status}" || true
    exit 1
esac

exit 0
