#! /usr/bin/python
# Copyright (c) 2016, Kevin Rodgers
# Released subject to the New BSD License
# Please see http://en.wikipedia.org/wiki/BSD_licenses

import os
import sys
import getopt
import logging
from active_mail_filter import amf_config
from active_mail_filter.rest_client import delete_url

logger = logging.getLogger(amf_config.logging.logger)

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '-u <uuid> '
         '[-s <source-folder>] '
         '[-t <target-folder>]\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    return 2


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'du:s:t:', [])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        sys.exit(usage())

    uuid = None
    for opt, arg in options:
        if opt == '-d':
            logger.setLevel(logging.DEBUG)
        elif opt == '-u':
            uuid = arg
        else:
            sys.exit(usage())

    if uuid is None:
        sys.exit(usage())

    url_route = '/show/%s' % uuid
    status, data = delete_url(url_route=url_route)
    if status != 204:
        print 'Error: %s' % str(data['message'])

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
