#! /usr/bin/python
# Copyright (c) 2016, Kevin Rodgers
# Released subject to the New BSD License
# Please see http://en.wikipedia.org/wiki/BSD_licenses

import os
import sys
import getopt
import logging
from active_mail_filter import amf_config, CONF_FILE

logger = logging.getLogger(amf_config.logging.logger)

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '[-r <redis-server> ]'
         '[-k <redis-key>] '
         '[-l <log-level>] '
         '[-c <cipher-key>\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    return 2


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'r:k:l:c:', [])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        sys.exit(usage())

    for opt, arg in options:
        if opt == '-r':
            amf_config.redis_server.redis_server = arg
        elif opt == '-k':
            amf_config.redis_server.redis_key = arg
        elif opt == '-c':
            amf_config.redis_server.cipher_key = arg
        elif opt == '-l':
            amf_config.logger.log_level = arg
        else:
            sys.exit(usage())

    with open(CONF_FILE, 'w+') as handle:
        amf_config.write(handle)
    handle.close()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
