#! /usr/bin/python
# Copyright (c) 2016, Kevin Rodgers
# Released subject to the New BSD License
# Please see http://en.wikipedia.org/wiki/BSD_licenses

import os
import sys
import getopt
import logging
from active_mail_filter import amf_config
from active_mail_filter.rest_client import get_url, post_url, put_url

logger = logging.getLogger(amf_config.logging.logger)

PROGNAME = os.path.basename(sys.argv[0])
USAGE = ('Usage: {0} '
         '-i <uuid> '
         '-u <username> '
         '-p <password> '
         '-e <email> '
         '-i <imap-server> '
         '-s <source-folder> '
         '-t <target-folder>\n'.format(PROGNAME))


def usage():
    sys.stderr.write(USAGE)
    return 2


def print_folders(folders):
    print 'Valid folders are...'
    for f in sorted(folders):
        print '\t' + f


def main():
    try:
        options, remainder = getopt.getopt(sys.argv[1:], 'di:u:p:e:i:s:t:', [])
    except getopt.GetoptError as err:
        sys.stderr.write('{0!s}\n'.format(err))
        sys.exit(usage())

    uuid = None
    user = None
    password = None
    email = None
    mail_server = None
    source = None
    target = None
    for opt, arg in options:
        if opt == '-d':
            logger.setLevel(logging.DEBUG)
        elif opt == '-i':
            uuid = arg
        elif opt == '-u':
            user = arg
        elif opt == '-p':
            password = arg
        elif opt == '-e':
            email = arg
        elif opt == '-i':
            mail_server = arg
        elif opt == '-s':
            source = arg
        elif opt == '-t':
            target = arg
        else:
            sys.exit(usage())

    if uuid is None:
        sys.exit(usage())

    params = {'user': user,
              'email': email,
              'password': password,
              'mail_server': mail_server,
              'source': source,
              'target': target}

    url_route = '/show/%s' % uuid
    status, data = get_url(url_route=url_route)
    if status != 200:
        print str(data)
        sys.exit(status)

    old_params = data['data']
    for key in params.keys():
        if key in old_params and params[key] is None:
            params[key] = old_params[key]
        if params[key] is None:
            del params[key]

    status, data = post_url(url_route='/folders', params=params)
    if status != 201:
        print 'Error: %s' % str(data['message'])
        sys.exit(status)

    # Special checks because inbox folder name is case insensitive
    folders = data['data'][params['user']]
    if params['source'].lower() != 'inbox' and params['source'] not in folders:
        print '%s: Invalid source folder' % source
        print_folders(folders)
        sys.exit(1)

    # can't use inbox as target folder
    if params['target'].lower() == 'inbox' or params['target'] not in folders:
        print '%s: Invalid target folder' % target
        print_folders(folders)
        sys.exit(1)

    url_route = '/update/%s' % uuid
    status, data = put_url(url_route=url_route, params=params)
    if status != 201:
        print 'Error: %s' % str(data['message'])
        sys.exit(status)

    print data['data']['uuid']

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
